"""create guests table

Revision ID: 12a89e844d2d
Revises: 
Create Date: 2026-06-15 17:42:14.732712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12a89e844d2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_name', sa.String(length=30), nullable=False),
    sa.Column('guest_phone_number', sa.String(length=20), nullable=False),
    sa.Column('guest_address', sa.String(length=300), nullable=False),
    sa.Column('id_proof_type', sa.String(length=20), nullable=False),
    sa.Column('id_proof_number', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guest_phone_number'),
    sa.UniqueConstraint('id_proof_number')
    )
    op.create_index(op.f('ix_guests_id'), 'guests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guests_id'), table_name='guests')
    op.drop_table('guests')
    # ### end Alembic commands ###
