"""create stays table

Revision ID: 77ee5b01ecb9
Revises: 12a89e844d2d
Create Date: 2026-06-16 11:52:00.429599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ee5b01ecb9'
down_revision: Union[str, Sequence[str], None] = '12a89e844d2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stays',
    sa.Column('stay_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('price_per_night', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('check_in_datetime', sa.DateTime(), nullable=False),
    sa.Column('check_out_datetime', sa.DateTime(), nullable=True),
    sa.Column('stay_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('stay_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stays')
    # ### end Alembic commands ###
