"""Create initial database schema

Revision ID: a421368a1c13
Revises: 
Create Date: 2026-06-20 17:18:49.148516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a421368a1c13'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_name', sa.String(length=30), nullable=False),
    sa.Column('guest_phone_number', sa.String(length=20), nullable=False),
    sa.Column('guest_address', sa.String(length=300), nullable=False),
    sa.Column('id_proof_type', sa.String(length=20), nullable=False),
    sa.Column('id_proof_number', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guest_phone_number'),
    sa.UniqueConstraint('id_proof_number')
    )
    op.create_index(op.f('ix_guests_id'), 'guests', ['id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('room_type', sa.String(length=50), nullable=True),
    sa.Column('price_per_night', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_occupancy', sa.Integer(), nullable=True),
    sa.Column('facilities', sa.String(length=500), nullable=True),
    sa.Column('room_status', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_number')
    )
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_table('system_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_info_id'), 'system_info', ['id'], unique=False)
    op.create_table('stays',
    sa.Column('stay_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('price_per_night', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('check_in_datetime', sa.DateTime(), nullable=False),
    sa.Column('check_out_datetime', sa.DateTime(), nullable=True),
    sa.Column('stay_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('stay_id')
    )
    op.create_table('guest_stays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('stay_id', sa.Integer(), nullable=False),
    sa.Column('is_primary_guest', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stay_id'], ['stays.stay_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guest_id', 'stay_id', name='uq_guest_stay')
    )
    op.create_index(op.f('ix_guest_stays_id'), 'guest_stays', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guest_stays_id'), table_name='guest_stays')
    op.drop_table('guest_stays')
    op.drop_table('stays')
    op.drop_index(op.f('ix_system_info_id'), table_name='system_info')
    op.drop_table('system_info')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_guests_id'), table_name='guests')
    op.drop_table('guests')
    # ### end Alembic commands ###
